---
name: default development workflow
on:
  workflow_call:
    inputs:
      project-type:
        description: 'The type of project. Can be "PYTHON_POETRY" or "PYTHON_SETUP_PY".'
        required: true
        type: string

jobs:
  prepare:
    name: prepare project
    uses: ./.github/workflows/_prepare.yml
    with:
      project-type: ${{ inputs.project-type }}
