---
name: prepare python project
on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: true
        description: "The version of Python to use."
      project-type:
        description: 'The type of project. Can be "PYTHON_POETRY" or "PYTHON_SETUP_PY".'
        required: true
        type: string

jobs:
  prepare-python-poetry:
    name: prepare Python project (Poetry)
    uses: ./.github/workflows/prepare-python-poetry.yml
    with:
      python-version: ${{ matrix.python-version }}
    if: ${{ inputs.project-type == 'PYTHON_POETRY' }}
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12]
  prepare-python-setup-py:
    name: prepare Python project (Setup.py)
    uses: ./.github/workflows/prepare-python-setup-py.yml
    if: ${{ inputs.project-type == 'PYTHON_SETUP_PY' }}
    with:
      python-version: ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12]