---
name: prepare project (Python, using Poetry)
on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: true
        description: "The version of Python to use."

jobs:
  build:
    name: prepare Python project (Poetry)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup a local virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v4
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv_${{ github.sha }}
      - name: Install dependencies
        run: |
          poetry install --with dev
