---
name: prepare python project
on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: true
        description: "The version of Python to use."
      project-type:
        description: 'The type of project. Can be "PYTHON_POETRY".'
        required: true
        type: string

jobs:
  prepare-python-poetry:
    name: prepare Python project (Poetry)
    uses: ./.github/workflows/prepare-python-poetry.yml
    with:
      python-version: ${{ inputs.python-version }}
    if: ${{ inputs.project-type == 'PYTHON_POETRY' }}