---
name: prepare project (Python, using Setup.py)
on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: "3.8"
        required: false
        description: "The version of Python to use."

jobs:
  prepare:
    name: prepare Python project (Setup.py)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install Pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
