---
name: run tests (pytest)
on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: true
        description: "The version of Python to use."

jobs:
  test:
    name: run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          update-environment: False
      - name: Retrieve the cache for the workflow
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: venv_${{ github.sha }}_${{ inputs.python-version }}
      - name: Active venv
        run: |
          source .venv/bin/activate
          echo "PATH=$PATH" >> $GITHUB_ENV
          echo $PATH
      - name: Run `pytest`
        run: pytest
