---
name: prepare project (Python, using Setup.py)
on:
  workflow_call:

jobs:
  prepare:
    name: prepare Python project (Setup.py)
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve the cache for the workflow
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Run pytest
        run: poetry run pytest
