---
name: workflow for python project
on:
  workflow_call:
    inputs:
      project-type:
        description: 'The type of project. Can be "PYTHON_POETRY" or "PYTHON_SETUP_PY".'
        required: true
        type: string

jobs:
  prepare-project:
    name: prepare project
    uses: ./.github/workflows/prepare-python.yml
    with:
      project-type: ${{ inputs.project-type }}
