---
name: workflow for python project
on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: "3.8"
        required: true
        description: "The version of Python to use."
      project-type:
        description: 'The type of project. Can be "PYTHON_POETRY" or "PYTHON_SETUP_PY".'
        required: true
        type: string
      test-suite:
        description: 'The test-suite that is being used. Can be "NONE" or "PYTEST".'
        required: true
        type: string
        default: 'NONE'

jobs:
  prepare-project:
    name: prepare project
    uses: ./.github/workflows/prepare-python.yml
    with:
      project-type: ${{ inputs.project-type }}
      python-version: ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
  test:
    name: run tests
    needs: prepare-project
    uses: ./.github/workflows/test-python.yml
    with:
      test-suite: ${{ inputs.test-suite }}
      python-version: ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    if: ${{ inputs.test-suite != 'NONE' }}
